### ISSUE TITLE
Add Binder support

### ISSUE THREAD

**Issue by matthewfeickert** [glouppe/paper-learning-to-pivot#17]
Hi @glouppe. A few people on ATLAS are trying to reproduce the results of this repo and so to make it easier I thought I would just Binderize it &mdash; which I'm in the process of doing now (mostly just pinning dependencies due to Theano being used and deprecation of APIs since publication).

It was clear from the comment in [`Jets.ipynb`](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/Jets.ipynb) that the HDF5 datasets being used were the ones at http://www.igb.uci.edu/~pfbaldi/physics/data/hepjets/highlevel/ which would need to be downloaded, but [in `jets.py` there is ](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/jets.py#L16)

```python
# Prepare data
fd = open("jets-pile.pickle", "rb")
``` 

I'm assuming that `jets-pile.pickle` is just the pickling the output of

```python
X_train, X_test, y_train, y_test, z_train, z_test = train_test_split(X, y, z, test_size=25000, random_state=1, stratify=strates)
```
in [`Jets.ipynb`](https://github.com/glouppe/paper-learning-to-pivot/blob/ae54635bf862af0dd93c53818ea3e95b2373f4dd/code/Jets.ipynb), correct? Nothing else was done?

**Comment by glouppe** [comment]
Hi Matthew!

Thanks for taking care of this. I do not remember exactly, but I think the content of `jets-pile.pickle` corresponds to those 6 arrays right after Cell 4 in the notebook.

(In general, it might be even better maybe to have a pytorch/tf/keras template for the pivot code, such that it is easy to adapt for anyone interested.)

Cheers,
Gilles

**Comment by matthewfeickert** [comment]
Thanks for the speedy reply, @glouppe!

> I do not remember exactly, but I think the content of `jets-pile.pickle` corresponds to those 6 arrays right after Cell 4 in the notebook.

Ah yes, I was too hasty. It is obviously important to include the
```python
X_train = X_train[:150000]
y_train = y_train[:150000]
z_train = z_train[:150000]
```

in what is pickled as well. Thanks for pointing that out!

Do you mind if I make an small edits to the notebooks themselves in this PR I'm going to be opening (such as adding in this pickle command)?

> (In general, it might be even better maybe to have a pytorch/tf/keras template for the pivot code, such that it is easy to adapt for anyone interested.)

I agree. If I want an extra distraction from writing my thesis by starting some of this would you want these templates added to this repo? Or do you want to preserve it as much as possible to be as it was when the paper was published and have these exist in another repo that would be linked in the `README`?

**Comment by glouppe** [comment]
> Do you mind if I make small edits to the notebooks themselves in this PR I'm going to be opening (such as adding in this pickle command)?

Please go ahead!
